PACKAGE_NAME="ks3fs"
PACKAGE_VERSION="0.3.1"
BUILT_MODULE_NAME[0]="ks3fs"
BUILT_MODULE_LOCATION[0]="src/"
DEST_MODULE_LOCATION[0]="/kernel/fs/ks3fs"
MAKE[0]="make -C src KVER=${kernelver} KDIR=${kernel_source_dir}"
CLEAN="make -C src clean KDIR=${kernel_source_dir}"
AUTOINSTALL="yes"
