#!/bin/bash
# Regenerate tests/nix/pins.env from a nixpkgs revision (needs nix on the
# host; CI only reads the committed pins).  The pinned stdenv must be in
# cache.nixos.org, i.e. come from a channel revision.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
REV=${1:?nixpkgs revision (channel commit)}
NP="github:NixOS/nixpkgs/$REV"
ev() { nix eval --raw "$NP#$1"; }
NIXVER=$(curl -fsS "http://nix-releases.s3.amazonaws.com/?list-type=2&delimiter=/&prefix=nix/" |
	grep -o 'nix/nix-2\.[0-9]*\.[0-9]*/' | sort -uV | tail -1 | sed 's|nix/nix-||;s|/||')
url=$(nix eval --raw "$NP#hello.src.urls" --apply 'u: builtins.head u' | sed 's|^mirror://gnu/|https://ftpmirror.gnu.org/|')
cat >"$ROOT/tests/nix/pins.env" <<PINS
# generated by tests/nix/gen-pins.sh $REV
NIXPKGS_REV=$REV
NIX_VERSION=$NIXVER
STDENV=$(ev stdenv.outPath)
STDENV_SHELL=$(ev stdenv.shell)
HELLO_VERSION=$(ev hello.version)
HELLO_URL=$url
HELLO_HASH=$(ev hello.src.outputHash)
PINS
cat "$ROOT/tests/nix/pins.env"
